export const GLOSSARY: Record<string, string> = {
  'Delta': 'How much the option price moves for every $1 the stock moves — like a gear ratio.',
  'Gamma': 'How fast Delta changes — high Gamma means the option sensitivity shifts rapidly.',
  'Theta': 'How much value the option loses per day just from time passing — options are melting ice cubes.',
  'Vega': 'How much the option price changes when market fear (volatility) goes up or down.',
  'Rho': 'How much the option price changes when interest rates move — usually the smallest effect.',
  'IV': 'Implied Volatility — how much the market expects the stock to move. High IV means expensive options.',
  'ATM': 'At-The-Money — the strike price is right at the current stock price.',
  'OTM': 'Out-of-The-Money — the strike is away from the current price, has no intrinsic value yet.',
  'ITM': 'In-The-Money — the option has real value if you exercised it right now.',
  'Premium': 'The price you pay (or receive) for one options contract.',
  'Strike': 'The pre-agreed price at which you can buy or sell the stock when you use the option.',
  'Expiry': 'The date the option expires — after this it becomes worthless if not used.',
  'Assignment': 'When a seller is forced to buy or sell stock because the buyer used their option.',
  'DTE': 'Days To Expiry — how many days before the option contract expires.',
  'Break-even': 'The stock price where you neither profit nor lose money at expiry.',
  'Max Profit': 'The best case — the most money you can make from this trade.',
  'Max Loss': 'The worst case — the most you can lose from this trade.',
  'Credit': 'Cash received upfront when selling options — yours to keep if the trade works out.',
  'Debit': 'Cash paid upfront to enter a trade — the most you can lose on some strategies.',
  'Margin': 'Cash your broker holds as collateral when you sell options, in case of large losses.',
  'Mark-to-Market': 'The current value of your position if you closed it right now at live prices.',
  '10Y Yield': 'The interest rate on 10-year US government bonds — when this rises, stocks often fall.',
  'DXY': 'The US Dollar Index — measures how strong the dollar is vs other major currencies.',
  'WTI': 'West Texas Intermediate crude oil price — the US benchmark for oil.',
  'VIX': 'The Fear Index — measures how much volatility the market expects over the next 30 days.',
  'ES Futures': 'S&P 500 futures contracts — trade 24/7 and show where the market is headed before open.',
};
