// Market instruments and strategy definitions

export interface Ticker {
  sym: string;
  name: string;
  seed: number;
  sector: string;
  type: 'Stock' | 'ETF';
}

export const TICKERS: Ticker[] = [
  // Index ETFs
  { sym: 'SPY',   name: 'SPDR S&P 500 ETF',           seed: 562,  sector: 'Index ETF',  type: 'ETF' },
  { sym: 'QQQ',   name: 'Invesco QQQ Trust',           seed: 473,  sector: 'Index ETF',  type: 'ETF' },
  { sym: 'IWM',   name: 'iShares Russell 2000',        seed: 208,  sector: 'Index ETF',  type: 'ETF' },
  { sym: 'DIA',   name: 'SPDR Dow Jones ETF',          seed: 440,  sector: 'Index ETF',  type: 'ETF' },
  { sym: 'VIX',   name: 'CBOE Volatility Index',       seed: 18,   sector: 'Index ETF',  type: 'ETF' },
  { sym: 'UVXY',  name: 'ProShares Ultra VIX',         seed: 9,    sector: 'Index ETF',  type: 'ETF' },
  { sym: 'SQQQ',  name: 'ProShares UltraPro Short QQQ',seed: 10,   sector: 'Index ETF',  type: 'ETF' },
  { sym: 'TQQQ',  name: 'ProShares UltraPro QQQ',      seed: 60,   sector: 'Index ETF',  type: 'ETF' },
  // Mega Cap Tech
  { sym: 'AAPL',  name: 'Apple Inc.',                  seed: 220,  sector: 'Tech',       type: 'Stock' },
  { sym: 'MSFT',  name: 'Microsoft Corp.',             seed: 415,  sector: 'Tech',       type: 'Stock' },
  { sym: 'NVDA',  name: 'NVIDIA Corp.',                seed: 135,  sector: 'Tech',       type: 'Stock' },
  { sym: 'GOOGL', name: 'Alphabet Inc. (A)',           seed: 175,  sector: 'Tech',       type: 'Stock' },
  { sym: 'GOOG',  name: 'Alphabet Inc. (C)',           seed: 176,  sector: 'Tech',       type: 'Stock' },
  { sym: 'META',  name: 'Meta Platforms',              seed: 570,  sector: 'Tech',       type: 'Stock' },
  { sym: 'TSLA',  name: 'Tesla Inc.',                  seed: 280,  sector: 'Tech',       type: 'Stock' },
  { sym: 'AMZN',  name: 'Amazon.com Inc.',             seed: 205,  sector: 'Tech',       type: 'Stock' },
  { sym: 'AMD',   name: 'Advanced Micro Devices',      seed: 155,  sector: 'Tech',       type: 'Stock' },
  { sym: 'INTC',  name: 'Intel Corp.',                 seed: 22,   sector: 'Tech',       type: 'Stock' },
  { sym: 'ORCL',  name: 'Oracle Corp.',                seed: 165,  sector: 'Tech',       type: 'Stock' },
  { sym: 'CRM',   name: 'Salesforce Inc.',             seed: 285,  sector: 'Tech',       type: 'Stock' },
  { sym: 'ADBE',  name: 'Adobe Inc.',                  seed: 455,  sector: 'Tech',       type: 'Stock' },
  { sym: 'NOW',   name: 'ServiceNow Inc.',             seed: 860,  sector: 'Tech',       type: 'Stock' },
  { sym: 'SNOW',  name: 'Snowflake Inc.',              seed: 155,  sector: 'Tech',       type: 'Stock' },
  { sym: 'PLTR',  name: 'Palantir Technologies',       seed: 38,   sector: 'Tech',       type: 'Stock' },
  { sym: 'UBER',  name: 'Uber Technologies',           seed: 78,   sector: 'Tech',       type: 'Stock' },
  { sym: 'COIN',  name: 'Coinbase Global',             seed: 240,  sector: 'Tech',       type: 'Stock' },
  { sym: 'RBLX',  name: 'Roblox Corp.',                seed: 42,   sector: 'Tech',       type: 'Stock' },
  { sym: 'HOOD',  name: 'Robinhood Markets',           seed: 22,   sector: 'Tech',       type: 'Stock' },
  { sym: 'SHOP',  name: 'Shopify Inc.',                seed: 78,   sector: 'Tech',       type: 'Stock' },
  { sym: 'NET',   name: 'Cloudflare Inc.',             seed: 95,   sector: 'Tech',       type: 'Stock' },
  { sym: 'DDOG',  name: 'Datadog Inc.',                seed: 130,  sector: 'Tech',       type: 'Stock' },
  { sym: 'ZM',    name: 'Zoom Video Communications',  seed: 62,   sector: 'Tech',       type: 'Stock' },
  { sym: 'CRWD',  name: 'CrowdStrike Holdings',        seed: 350,  sector: 'Tech',       type: 'Stock' },
  { sym: 'PANW',  name: 'Palo Alto Networks',          seed: 185,  sector: 'Tech',       type: 'Stock' },
  { sym: 'SMCI',  name: 'Super Micro Computer',        seed: 850,  sector: 'Tech',       type: 'Stock' },
  { sym: 'MSTR',  name: 'MicroStrategy Inc.',          seed: 1700, sector: 'Tech',       type: 'Stock' },
  // Semis
  { sym: 'AVGO',  name: 'Broadcom Inc.',               seed: 1700, sector: 'Semis',      type: 'Stock' },
  { sym: 'QCOM',  name: 'Qualcomm Inc.',               seed: 165,  sector: 'Semis',      type: 'Stock' },
  { sym: 'MU',    name: 'Micron Technology',           seed: 105,  sector: 'Semis',      type: 'Stock' },
  { sym: 'AMAT',  name: 'Applied Materials',           seed: 190,  sector: 'Semis',      type: 'Stock' },
  { sym: 'LRCX',  name: 'Lam Research Corp.',          seed: 890,  sector: 'Semis',      type: 'Stock' },
  { sym: 'KLAC',  name: 'KLA Corp.',                   seed: 820,  sector: 'Semis',      type: 'Stock' },
  { sym: 'SOXX',  name: 'iShares Semiconductor ETF',   seed: 230,  sector: 'Semis',      type: 'ETF' },
  { sym: 'SMH',   name: 'VanEck Semiconductor ETF',    seed: 235,  sector: 'Semis',      type: 'ETF' },
  // Finance
  { sym: 'JPM',   name: 'JPMorgan Chase',              seed: 220,  sector: 'Finance',    type: 'Stock' },
  { sym: 'GS',    name: 'Goldman Sachs',               seed: 510,  sector: 'Finance',    type: 'Stock' },
  { sym: 'MS',    name: 'Morgan Stanley',              seed: 105,  sector: 'Finance',    type: 'Stock' },
  { sym: 'BAC',   name: 'Bank of America',             seed: 42,   sector: 'Finance',    type: 'Stock' },
  { sym: 'WFC',   name: 'Wells Fargo & Co.',           seed: 62,   sector: 'Finance',    type: 'Stock' },
  { sym: 'C',     name: 'Citigroup Inc.',              seed: 68,   sector: 'Finance',    type: 'Stock' },
  { sym: 'V',     name: 'Visa Inc.',                   seed: 285,  sector: 'Finance',    type: 'Stock' },
  { sym: 'MA',    name: 'Mastercard Inc.',             seed: 490,  sector: 'Finance',    type: 'Stock' },
  { sym: 'AXP',   name: 'American Express Co.',        seed: 260,  sector: 'Finance',    type: 'Stock' },
  { sym: 'PYPL',  name: 'PayPal Holdings',             seed: 72,   sector: 'Finance',    type: 'Stock' },
  { sym: 'SQ',    name: 'Block Inc.',                  seed: 72,   sector: 'Finance',    type: 'Stock' },
  { sym: 'XLF',   name: 'Financial Select SPDR ETF',   seed: 44,   sector: 'Finance',    type: 'ETF' },
  { sym: 'BRK-B', name: 'Berkshire Hathaway B',        seed: 455,  sector: 'Finance',    type: 'Stock' },
  // Energy
  { sym: 'XOM',   name: 'Exxon Mobil Corp.',           seed: 112,  sector: 'Energy',     type: 'Stock' },
  { sym: 'CVX',   name: 'Chevron Corp.',               seed: 155,  sector: 'Energy',     type: 'Stock' },
  { sym: 'COP',   name: 'ConocoPhillips',              seed: 105,  sector: 'Energy',     type: 'Stock' },
  { sym: 'SLB',   name: 'SLB (Schlumberger)',          seed: 42,   sector: 'Energy',     type: 'Stock' },
  { sym: 'OXY',   name: 'Occidental Petroleum',        seed: 52,   sector: 'Energy',     type: 'Stock' },
  { sym: 'MRO',   name: 'Marathon Oil Corp.',          seed: 27,   sector: 'Energy',     type: 'Stock' },
  { sym: 'USO',   name: 'United States Oil Fund',      seed: 78,   sector: 'Energy',     type: 'ETF' },
  { sym: 'XLE',   name: 'Energy Select SPDR ETF',      seed: 90,   sector: 'Energy',     type: 'ETF' },
  // Healthcare
  { sym: 'JNJ',   name: 'Johnson & Johnson',           seed: 145,  sector: 'Healthcare', type: 'Stock' },
  { sym: 'PFE',   name: 'Pfizer Inc.',                 seed: 28,   sector: 'Healthcare', type: 'Stock' },
  { sym: 'MRNA',  name: 'Moderna Inc.',                seed: 72,   sector: 'Healthcare', type: 'Stock' },
  { sym: 'ABBV',  name: 'AbbVie Inc.',                 seed: 190,  sector: 'Healthcare', type: 'Stock' },
  { sym: 'LLY',   name: 'Eli Lilly and Co.',           seed: 800,  sector: 'Healthcare', type: 'Stock' },
  { sym: 'UNH',   name: 'UnitedHealth Group',          seed: 560,  sector: 'Healthcare', type: 'Stock' },
  { sym: 'BIIB',  name: 'Biogen Inc.',                 seed: 205,  sector: 'Healthcare', type: 'Stock' },
  { sym: 'GILD',  name: 'Gilead Sciences',             seed: 85,   sector: 'Healthcare', type: 'Stock' },
  { sym: 'REGN',  name: 'Regeneron Pharmaceuticals',   seed: 900,  sector: 'Healthcare', type: 'Stock' },
  { sym: 'XBI',   name: 'SPDR S&P Biotech ETF',        seed: 92,   sector: 'Healthcare', type: 'ETF' },
  { sym: 'XLV',   name: 'Health Care Select SPDR ETF', seed: 148,  sector: 'Healthcare', type: 'ETF' },
  // Consumer
  { sym: 'WMT',   name: 'Walmart Inc.',                seed: 90,   sector: 'Consumer',   type: 'Stock' },
  { sym: 'COST',  name: 'Costco Wholesale',            seed: 920,  sector: 'Consumer',   type: 'Stock' },
  { sym: 'TGT',   name: 'Target Corp.',                seed: 148,  sector: 'Consumer',   type: 'Stock' },
  { sym: 'HD',    name: 'Home Depot Inc.',             seed: 390,  sector: 'Consumer',   type: 'Stock' },
  { sym: 'NKE',   name: 'Nike Inc.',                   seed: 72,   sector: 'Consumer',   type: 'Stock' },
  { sym: 'MCD',   name: "McDonald's Corp.",            seed: 298,  sector: 'Consumer',   type: 'Stock' },
  { sym: 'SBUX',  name: 'Starbucks Corp.',             seed: 88,   sector: 'Consumer',   type: 'Stock' },
  { sym: 'DIS',   name: 'Walt Disney Co.',             seed: 112,  sector: 'Consumer',   type: 'Stock' },
  { sym: 'NFLX',  name: 'Netflix Inc.',                seed: 680,  sector: 'Consumer',   type: 'Stock' },
  { sym: 'SPOT',  name: 'Spotify Technology',          seed: 360,  sector: 'Consumer',   type: 'Stock' },
  // Industrial
  { sym: 'BA',    name: 'Boeing Co.',                  seed: 175,  sector: 'Industrial', type: 'Stock' },
  { sym: 'CAT',   name: 'Caterpillar Inc.',            seed: 360,  sector: 'Industrial', type: 'Stock' },
  { sym: 'GE',    name: 'GE Aerospace',                seed: 170,  sector: 'Industrial', type: 'Stock' },
  { sym: 'LMT',   name: 'Lockheed Martin Corp.',       seed: 490,  sector: 'Industrial', type: 'Stock' },
  { sym: 'RTX',   name: 'RTX Corp.',                   seed: 124,  sector: 'Industrial', type: 'Stock' },
  { sym: 'NOC',   name: 'Northrop Grumman Corp.',      seed: 488,  sector: 'Industrial', type: 'Stock' },
  { sym: 'UPS',   name: 'United Parcel Service',       seed: 130,  sector: 'Industrial', type: 'Stock' },
  { sym: 'FDX',   name: 'FedEx Corp.',                 seed: 255,  sector: 'Industrial', type: 'Stock' },
  // Commodities / Bonds
  { sym: 'GLD',   name: 'SPDR Gold Shares',            seed: 230,  sector: 'Commodities',type: 'ETF' },
  { sym: 'SLV',   name: 'iShares Silver Trust',        seed: 28,   sector: 'Commodities',type: 'ETF' },
  { sym: 'GDX',   name: 'VanEck Gold Miners ETF',      seed: 37,   sector: 'Commodities',type: 'ETF' },
  { sym: 'GDXJ',  name: 'VanEck Junior Gold Miners',   seed: 44,   sector: 'Commodities',type: 'ETF' },
  { sym: 'DBA',   name: 'Invesco DB Agriculture ETF',  seed: 22,   sector: 'Commodities',type: 'ETF' },
  { sym: 'TLT',   name: 'iShares 20+ Year Treasury',   seed: 92,   sector: 'Bonds',      type: 'ETF' },
  { sym: 'HYG',   name: 'iShares High Yield Corp Bond',seed: 79,   sector: 'Bonds',      type: 'ETF' },
  { sym: 'LQD',   name: 'iShares Investment Grade Corp',seed: 108, sector: 'Bonds',      type: 'ETF' },
  // China ADRs
  { sym: 'BABA',  name: 'Alibaba Group',               seed: 88,   sector: 'China ADR',  type: 'Stock' },
  { sym: 'BIDU',  name: 'Baidu Inc.',                  seed: 88,   sector: 'China ADR',  type: 'Stock' },
  { sym: 'JD',    name: 'JD.com Inc.',                 seed: 32,   sector: 'China ADR',  type: 'Stock' },
  { sym: 'PDD',   name: 'PDD Holdings',                seed: 140,  sector: 'China ADR',  type: 'Stock' },
  { sym: 'NIO',   name: 'NIO Inc.',                    seed: 5,    sector: 'China ADR',  type: 'Stock' },
  { sym: 'XPEV',  name: 'XPeng Inc.',                  seed: 12,   sector: 'China ADR',  type: 'Stock' },
  { sym: 'LI',    name: 'Li Auto Inc.',                seed: 22,   sector: 'China ADR',  type: 'Stock' },
  { sym: 'FXI',   name: 'iShares China Large-Cap ETF', seed: 28,   sector: 'China ADR',  type: 'ETF' },
  { sym: 'KWEB',  name: 'KraneShares CSI China Internet',seed: 30, sector: 'China ADR',  type: 'ETF' },
  // Crypto-linked
  { sym: 'IBIT',  name: 'iShares Bitcoin Trust',       seed: 52,   sector: 'Crypto',     type: 'ETF' },
  { sym: 'FBTC',  name: 'Fidelity Wise Origin Bitcoin',seed: 52,   sector: 'Crypto',     type: 'ETF' },
  { sym: 'MARA',  name: 'Marathon Digital Holdings',   seed: 18,   sector: 'Crypto',     type: 'Stock' },
  { sym: 'RIOT',  name: 'Riot Platforms Inc.',         seed: 10,   sector: 'Crypto',     type: 'Stock' },
  // Real Estate
  { sym: 'VNQ',   name: 'Vanguard Real Estate ETF',    seed: 87,   sector: 'Real Estate',type: 'ETF' },
  { sym: 'AMT',   name: 'American Tower Corp.',        seed: 210,  sector: 'Real Estate',type: 'Stock' },
  // Telecom
  { sym: 'T',     name: 'AT&T Inc.',                   seed: 19,   sector: 'Telecom',    type: 'Stock' },
  { sym: 'VZ',    name: 'Verizon Communications',      seed: 42,   sector: 'Telecom',    type: 'Stock' },
  // EV/Clean
  { sym: 'RIVN',  name: 'Rivian Automotive',           seed: 12,   sector: 'EV/Clean',   type: 'Stock' },
  { sym: 'LCID',  name: 'Lucid Group Inc.',            seed: 3,    sector: 'EV/Clean',   type: 'Stock' },
  { sym: 'ENPH',  name: 'Enphase Energy',              seed: 88,   sector: 'EV/Clean',   type: 'Stock' },
  { sym: 'FSLR',  name: 'First Solar Inc.',            seed: 165,  sector: 'EV/Clean',   type: 'Stock' },
  { sym: 'ICLN',  name: 'iShares Global Clean Energy', seed: 14,   sector: 'EV/Clean',   type: 'ETF' },
  // Meme
  { sym: 'GME',   name: 'GameStop Corp.',              seed: 22,   sector: 'Meme',       type: 'Stock' },
  { sym: 'AMC',   name: 'AMC Entertainment',           seed: 4,    sector: 'Meme',       type: 'Stock' },
  // Staples
  { sym: 'PG',    name: 'Procter & Gamble Co.',        seed: 168,  sector: 'Staples',    type: 'Stock' },
  { sym: 'KO',    name: 'Coca-Cola Co.',               seed: 63,   sector: 'Staples',    type: 'Stock' },
  { sym: 'PEP',   name: 'PepsiCo Inc.',                seed: 165,  sector: 'Staples',    type: 'Stock' },
  // Pharma
  { sym: 'MRK',   name: 'Merck & Co.',                 seed: 122,  sector: 'Pharma',     type: 'Stock' },
  { sym: 'BMY',   name: 'Bristol-Myers Squibb',        seed: 48,   sector: 'Pharma',     type: 'Stock' },
  // Volatility ETFs
  { sym: 'VXX',   name: 'iPath Series B S&P 500 VIX',  seed: 22,   sector: 'Volatility', type: 'ETF' },
  { sym: 'SVXY',  name: 'ProShares Short VIX ETF',     seed: 52,   sector: 'Volatility', type: 'ETF' },
  { sym: 'VIXY',  name: 'ProShares VIX Short-Term ETF',seed: 14,   sector: 'Volatility', type: 'ETF' },
  // Sector ETFs
  { sym: 'XLK',   name: 'Technology Select SPDR ETF',  seed: 220,  sector: 'Sector ETF', type: 'ETF' },
  { sym: 'XLI',   name: 'Industrial Select SPDR ETF',  seed: 130,  sector: 'Sector ETF', type: 'ETF' },
  { sym: 'XLP',   name: 'Consumer Staples SPDR ETF',   seed: 78,   sector: 'Sector ETF', type: 'ETF' },
  { sym: 'XLY',   name: 'Consumer Discret. SPDR ETF',  seed: 198,  sector: 'Sector ETF', type: 'ETF' },
  { sym: 'XLB',   name: 'Materials Select SPDR ETF',   seed: 88,   sector: 'Sector ETF', type: 'ETF' },
  { sym: 'ARKK',  name: 'ARK Innovation ETF',          seed: 48,   sector: 'Sector ETF', type: 'ETF' },
  { sym: 'ARKG',  name: 'ARK Genomic Revolution ETF',  seed: 22,   sector: 'Sector ETF', type: 'ETF' },
];

export const STRATEGIES: Record<string, { risk: 'Low' | 'Med' | 'High'; view: string; legs: number }> = {
  'Covered Call':     { risk: 'Low',  view: 'Neutral to mildly bullish',                    legs: 1 },
  'Protective Put':   { risk: 'Low',  view: 'Bullish with downside protection',             legs: 1 },
  'Bull Call Spread': { risk: 'Med',  view: 'Moderately bullish',                           legs: 2 },
  'Bear Put Spread':  { risk: 'Med',  view: 'Moderately bearish',                           legs: 2 },
  'Bull Put Spread':  { risk: 'Med',  view: 'Bullish / neutral',                            legs: 2 },
  'Bear Call Spread': { risk: 'Med',  view: 'Bearish / neutral',                            legs: 2 },
  'Long Straddle':    { risk: 'Med',  view: 'Big move expected, direction unknown',          legs: 2 },
  'Short Straddle':   { risk: 'High', view: 'Low volatility, range-bound',                  legs: 2 },
  'Long Strangle':    { risk: 'Med',  view: 'Big move expected, cheaper than straddle',     legs: 2 },
  'Short Strangle':   { risk: 'High', view: 'Range-bound, sell premium',                    legs: 2 },
  'Iron Condor':      { risk: 'Med',  view: 'Neutral, range-bound',                         legs: 4 },
  'Iron Butterfly':   { risk: 'Med',  view: 'Neutral, low vol',                             legs: 4 },
  'Collar':           { risk: 'Low',  view: 'Hold stock, limit risk',                       legs: 2 },
  'Butterfly Spread': { risk: 'Low',  view: 'Pinpoint neutral',                             legs: 4 },
  'Calendar Spread':  { risk: 'Med',  view: 'Neutral short-term, directional longer',       legs: 2 },
  'Diagonal Spread':  { risk: 'Med',  view: 'Directional with time decay benefit',          legs: 2 },
  'The Wheel':        { risk: 'Med',  view: 'Income generation on stock you want to own',   legs: 1 },
  'Cash-Secured Put': { risk: 'Med',  view: 'Bullish, earn premium while waiting to buy',   legs: 1 },
  'Put Ratio Spread': { risk: 'High', view: 'Bearish with defined upside risk',             legs: 3 },
  'Risk Reversal':    { risk: 'High', view: 'Strongly bullish, leveraged',                  legs: 2 },
};

export const STRATEGY_EXPLANATIONS: Record<string, { simple: string; when: string; pros: string; cons: string; layman: string }> = {
  'Covered Call': {
    simple: 'Own the stock, sell a call above current price to earn premium income.',
    when: 'You own shares and expect the stock to stay flat or rise slightly.',
    pros: 'Generates income, reduces cost basis.',
    cons: 'Caps your upside if stock surges.',
    layman: 'Like renting out your shares — you get paid cash but promise not to sell above a set price.',
  },
  'Protective Put': {
    simple: 'Buy a put below current price to insure against a large drop.',
    when: 'You own shares but fear a short-term pullback.',
    pros: 'Limits downside to the strike minus premium paid.',
    cons: 'Premium cost reduces overall returns.',
    layman: 'Like insurance on your shares — pay a small fee to guarantee a minimum sell price.',
  },
  'Bull Call Spread': {
    simple: 'Buy a lower-strike call, sell a higher-strike call. Profit between the two strikes.',
    when: 'You expect a moderate rise in price.',
    pros: 'Lower cost than buying a call outright; defined risk.',
    cons: 'Capped profit; loses if stock stays flat or falls.',
    layman: 'Bet the stock rises but cap both profit and loss — cheaper than buying a plain call.',
  },
  'Bear Put Spread': {
    simple: 'Buy a higher-strike put, sell a lower-strike put. Profit on a moderate decline.',
    when: 'You expect the stock to fall moderately.',
    pros: 'Defined risk and reward; cheaper than buying a put outright.',
    cons: 'Profit is capped at the spread width.',
    layman: 'Bet the stock falls with a safety net — you can only lose what you paid upfront.',
  },
  'Bull Put Spread': {
    simple: 'Sell a put and buy a lower-strike put. Collect premium if stock stays above short strike.',
    when: 'Neutral to bullish; you want to sell premium with limited risk.',
    pros: 'Defined risk; credit received upfront.',
    cons: 'Limited profit; full loss if stock collapses.',
    layman: "Collect cash upfront by betting the stock won't fall below a level — keep it if right.",
  },
  'Bear Call Spread': {
    simple: 'Sell a lower-strike call, buy a higher-strike call. Collect premium in range-bound or falling market.',
    when: 'You expect the stock to stay flat or fall.',
    pros: 'Defined risk; credit received upfront.',
    cons: 'Limited profit; full loss if stock surges past long strike.',
    layman: "Collect cash upfront by betting the stock won't rise above a level — keep it if right.",
  },
  'Long Straddle': {
    simple: 'Buy a call and put at the same strike. Profit from a big move in either direction.',
    when: 'Earnings, FDA approval, or other binary events are expected.',
    pros: 'Unlimited profit potential in either direction.',
    cons: 'Expensive; needs a very large move to be profitable.',
    layman: 'Bet the stock will make a big move — direction does not matter, just needs to move a lot.',
  },
  'Short Straddle': {
    simple: 'Sell a call and put at the same strike. Profit if the stock barely moves.',
    when: 'You expect low volatility and a quiet market.',
    pros: 'Maximum premium collected; profits from time decay.',
    cons: 'Unlimited risk if stock makes a big move.',
    layman: 'Bet the stock barely moves — collect cash upfront and keep it if the stock stays calm.',
  },
  'Long Strangle': {
    simple: 'Buy an OTM call and OTM put. Cheaper than straddle, needs even bigger move.',
    when: 'Expecting a large move but want to pay less premium than a straddle.',
    pros: 'Lower cost than straddle; profits from big moves.',
    cons: 'Needs a larger move than straddle to break even.',
    layman: 'Cheaper straddle — bet on a big move either way, needs an even bigger move to profit.',
  },
  'Short Strangle': {
    simple: 'Sell an OTM call and OTM put. Profit in a range-bound market.',
    when: 'You expect low volatility and the stock to stay in a range.',
    pros: 'Wider profit zone than short straddle.',
    cons: 'Unlimited risk beyond the short strikes.',
    layman: 'Sell two options and collect cash — profit as long as the stock stays in a quiet range.',
  },
  'Iron Condor': {
    simple: 'Sell OTM call + put spreads. Profit if stock stays in a range.',
    when: 'Range-bound market; great for earning theta in flat periods.',
    pros: 'Defined risk; profits from time decay and low vol.',
    cons: 'Limited profit; loses if stock breaks out of the range.',
    layman: 'A 4-option trade that profits when the stock does nothing exciting — like betting for boring weather.',
  },
  'Iron Butterfly': {
    simple: 'Sell ATM call + put, buy OTM call + put. Profit near current price.',
    when: 'Stock is range-bound and you expect minimal movement.',
    pros: 'Higher premium than iron condor; profits from low vol.',
    cons: 'Narrower profit zone; needs stock to stay near center strike.',
    layman: 'Like Iron Condor but narrower — higher payout if stock pins exactly at your target price.',
  },
  'Collar': {
    simple: 'Own stock + buy put + sell call. Limits both upside and downside.',
    when: 'You want to protect gains on a stock position at low or no cost.',
    pros: 'Downside protection; often zero-cost if structured correctly.',
    cons: 'Caps upside; may miss large rallies.',
    layman: 'Own a stock, buy a floor below and sell a ceiling above — no big wins or big losses.',
  },
  'Butterfly Spread': {
    simple: 'Buy low strike + buy high strike calls, sell 2 ATM calls. Max profit at middle strike.',
    when: 'You expect the stock to pin near a specific price at expiry.',
    pros: 'Defined risk; good reward/risk ratio near center strike.',
    cons: 'Very narrow profit zone; needs precise price prediction.',
    layman: 'A precise bet the stock lands at one price at expiry — very cheap, very specific.',
  },
  'Calendar Spread': {
    simple: 'Sell near-term option, buy longer-dated option at the same strike.',
    when: 'Stock is neutral short-term but may move later; also good for IV crush after events.',
    pros: 'Benefits from time decay difference; relatively cheap.',
    cons: 'Complex to manage; sensitive to IV changes.',
    layman: 'Sell a short-term option and buy a longer one — profit from the short one decaying faster.',
  },
  'Diagonal Spread': {
    simple: 'Sell near-term OTM option, buy longer-dated ATM option at different strikes.',
    when: 'Directional bias with a time decay advantage.',
    pros: 'More directional than calendar; benefits from time decay.',
    cons: 'Complex; requires adjustment as near-term option expires.',
    layman: 'Like Calendar Spread but with different strikes — directional bet plus time decay benefit.',
  },
  'The Wheel': {
    simple: 'Sell CSP → get assigned → sell covered call → repeat for income.',
    when: 'You want to own a stock at a lower price and generate income while waiting.',
    pros: 'Consistent income; can acquire stock at discount.',
    cons: 'Ties up capital; full downside risk on stock ownership.',
    layman: 'Income machine: sell a put to get paid, get the stock, then sell covered calls repeatedly.',
  },
  'Cash-Secured Put': {
    simple: 'Sell a put while holding enough cash to buy the shares if assigned.',
    when: 'Bullish on a stock; want to buy at a lower price or earn premium.',
    pros: 'Earn premium while waiting; effective lower entry price.',
    cons: 'Miss large rallies; full downside if stock crashes.',
    layman: 'Get paid to agree to buy a stock at a lower price — keep the cash if it never falls there.',
  },
  'Put Ratio Spread': {
    simple: 'Buy 1 ATM put, sell 2 lower-strike puts. Bearish with a twist below lower strike.',
    when: 'Moderately bearish; want to profit from moderate decline.',
    pros: 'Can be entered for a credit; profits in moderate bear move.',
    cons: 'Large losses if stock crashes far below lower strike.',
    layman: 'Bearish bet with a trap door — profits on moderate falls but loses big in a crash.',
  },
  'Risk Reversal': {
    simple: 'Sell OTM put, buy OTM call. Bullish position, often for zero or low cost.',
    when: 'Strongly bullish; want leveraged exposure with minimal premium.',
    pros: 'Low cost or credit; leveraged upside.',
    cons: 'Full downside risk below the short put strike.',
    layman: 'Bullish bet by selling a put and buying a call — often costs little or nothing upfront.',
  },
};

// Sector colour mapping
export const SECTOR_COLORS: Record<string, string> = {
  'Tech':        '#60a5fa',
  'Finance':     '#34d399',
  'Index ETF':   '#c9a84c',
  'Semis':       '#818cf8',
  'Energy':      '#fb923c',
  'Healthcare':  '#a78bfa',
  'Consumer':    '#f472b6',
  'Industrial':  '#94a3b8',
  'Commodities': '#fbbf24',
  'Bonds':       '#6ee7b7',
  'China ADR':   '#f87171',
  'Crypto':      '#f59e0b',
  'Real Estate': '#4ade80',
  'Telecom':     '#38bdf8',
  'EV/Clean':    '#86efac',
  'Meme':        '#e879f9',
  'Staples':     '#a3e635',
  'Pharma':      '#c084fc',
  'Volatility':  '#fb7185',
  'Sector ETF':  '#e2c97e',
};
